In [17]:
# If you see a test failure when checking your solution,
# note that [left] refers to YOUR code while [right]
# refers to the correct code that the computer is comparing
# to your work

# Let's start by importing pandas below
import pandas as pd

In [18]:
# This challenge includes a the_office.csv dataset.
# It is a listing of all episodes in the popular American sitcom The Office.
# The dataset has 7 columns:
# Season, Episode, Name, Director, Writer, Airdate, Viewership
# Import the the_office.csv file into a DataFrame. 
# Tell pandas to parse the values in the Airdate column as datetime values.
# Finally, assign the imported DataFrame to an 'office' variable.
office = pd.read_csv('the_office.csv', parse_dates=['Airdate'])
office.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Season      201 non-null    int64
 1   Episode     201 non-null    int64
 2   Name        201 non-null    object
 3   Director    201 non-null    object
 4   Writer      201 non-null    object
 5   Airdate     201 non-null    datetime64[ns]
 6   Viewership  201 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 11.1+ KB

In [19]:
office.head()

,Season,Episode,Name,Director,Writer,Airdate,Viewership
0,1,1,Pilot,Ken Kwapis,Ricky Gervais & Stephen Merchant and Greg Daniels,2005-03-24,11.2
1,1,2,Diversity Day,Ken Kwapis,B. J. Novak,2005-03-29,6.0
2,1,3,Health Care,Ken Whittingham,Paul Lieberstein,2005-04-05,5.8
3,1,4,The Alliance,Bryan Gordon,Michael Schur,2005-04-12,5.4
4,1,5,Basketball,Greg Daniels,Greg Daniels,2005-04-19,5.0

In [20]:
# CHALLENGE 1:
# Find all episodes with a Viewership greater than 10
# who are also directed by Jeffrey Blitz
# Assign the resulting DataFrame to a 'jeffs_episodes' variable.
viewership_greater_than_10 = office['Viewership'] > 10
directed_by_jeffs = office['Director'] == 'Jeffrey Blitz'
jeffs_episodes = office[viewership_greater_than_10 & directed_by_jeffs]
jeffs_episodes

,Season,Episode,Name,Director,Writer,Airdate,Viewership
85,5,14,Stress Relief,Jeffrey Blitz,Paul Lieberstein,2009-02-01,22.91
86,5,15,Stress Relief,Jeffrey Blitz,Paul Lieberstein,2009-02-01,22.91

In [21]:
# CHALLENGE 2:
# Find all episodes in season 5 that have an episode number
# greater than or equal to 13.
# Assign the resulting DataFrame to a "second_half_of_season_5" variable.
season_5 = office['Season'] == 5
greater_episode_13 = office['Episode'] >= 13
second_half_of_season_5 = office[greater_episode_13 & season_5]
second_half_of_season_5

,Season,Episode,Name,Director,Writer,Airdate,Viewership
84,5,13,Prince Family Paper,Asaad Kelada,B. J. Novak,2009-01-22,8.74
85,5,14,Stress Relief,Jeffrey Blitz,Paul Lieberstein,2009-02-01,22.91
86,5,15,Stress Relief,Jeffrey Blitz,Paul Lieberstein,2009-02-01,22.91
87,5,16,Lecture Circuit: Part 1,Ken Kwapis,Mindy Kaling,2009-02-05,8.39
88,5,17,Lecture Circuit: Part 2,Ken Kwapis,Mindy Kaling,2009-02-12,8.89
89,5,18,Blood Drive,Randall Einhorn,Brent Forrester,2009-03-05,8.63
90,5,19,Golden Ticket,Randall Einhorn,Mindy Kaling,2009-03-12,7.51
91,5,20,New Boss,Paul Feig,Lee Eisenberg & Gene Stupnitsky,2009-03-19,7.95
92,5,21,Two Weeks,Paul Lieberstein,Aaron Shure,2009-03-26,8.45
93,5,22,Dream Team,Paul Feig,B. J. Novak,2009-04-09,7.20
94,5,23,Michael Scott Paper Company,Gene Stupnitsky,Justin Spitzer,2009-04-09,7.94
95,5,24,Heavy Competition,Ken Whittingham,Ryan Koh,2009-04-16,8.24
96,5,25,Broke,Steve Carell,Charlie Grandy,2009-04-23,7.21
97,5,26,Casual Friday,Brent Forrester,Anthony Q. Farrell,2009-04-30,7.31
98,5,27,Cafe Disco,Randall Einhorn,Warren Lieberstein & Halsted Sullivan,2009-05-07,7.71
99,5,28,Company Picnic,Ken Kwapis,Jennifer Celotta & Paul Lieberstein,2009-05-14,6.72

In [24]:
# CHALLENGE 3:
# Find all episodes that were the 6th episode of their season
# and also aired before 01/01/2010.
# Assign the resulting DataFrame to a "sixth_episodes_of_early_seasons" variable.
sixth_episodes = office["Episode"] == 6
desired_airdate = office["Airdate"] < "01/01/2010"
sixth_episodes_of_early_seasons = office[sixth_episodes & desired_airdate]
sixth_episodes_of_early_seasons

,Season,Episode,Name,Director,Writer,Airdate,Viewership
5,1,6,Hot Girl,Amy Heckerling,Mindy Kaling,2005-04-26,4.80
11,2,6,The Fight,Ken Kwapis,Gene Stupnitsky & Lee Eisenberg,2005-11-01,7.90
33,3,6,Diwali,Miguel Arteta,Mindy Kaling,2006-11-02,8.81
58,4,6,Launch Party,Ken Whittingham,Jennifer Celotta,2007-10-11,8.91
77,5,6,Employee Transfer,David Rogers,Anthony Q. Farrell,2008-10-30,9.32
105,6,6,Mafia,David Rogers,Brent Forrester,2009-10-15,8.10